<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppliedCouponEligibilityCheckerInterfaceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\ApiBundle\Checker\AppliedCouponEligibilityCheckerInterface' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Checker\AppliedCouponEligibilityChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/Checker/AppliedCouponEligibilityCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/Checker/AppliedCouponEligibilityChecker.php';

        return $container->privates['Sylius\\Bundle\\ApiBundle\\Checker\\AppliedCouponEligibilityCheckerInterface'] = new \Sylius\Bundle\ApiBundle\Checker\AppliedCouponEligibilityChecker(($container->services['sylius.promotion_eligibility_checker'] ?? $container->load('getSylius_PromotionEligibilityCheckerService')), ($container->services['sylius.promotion_coupon_eligibility_checker'] ?? $container->load('getSylius_PromotionCouponEligibilityCheckerService')));
    }
}
