<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateLogEntryOnPriceChangeObserver2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\CoreBundle\PriceHistory\EntityObserver\CreateLogEntryOnPriceChangeObserver' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\PriceHistory\EntityObserver\CreateLogEntryOnPriceChangeObserver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/CoreBundle/PriceHistory/EntityObserver/EntityObserverInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/CoreBundle/PriceHistory/EntityObserver/CreateLogEntryOnPriceChangeObserver.php';

        $a = ($container->services['Sylius\\Bundle\\CoreBundle\\PriceHistory\\Logger\\PriceChangeLoggerInterface'] ?? $container->load('getPriceChangeLoggerInterface2Service'));

        if (isset($container->services['Sylius\\Bundle\\CoreBundle\\PriceHistory\\EntityObserver\\CreateLogEntryOnPriceChangeObserver'])) {
            return $container->services['Sylius\\Bundle\\CoreBundle\\PriceHistory\\EntityObserver\\CreateLogEntryOnPriceChangeObserver'];
        }

        return $container->services['Sylius\\Bundle\\CoreBundle\\PriceHistory\\EntityObserver\\CreateLogEntryOnPriceChangeObserver'] = new \Sylius\Bundle\CoreBundle\PriceHistory\EntityObserver\CreateLogEntryOnPriceChangeObserver($a);
    }
}
