<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreatingProductVariantContextService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sylius\Behat\Context\Api\Admin\CreatingProductVariantContext' shared service.
     *
     * @return \Sylius\Behat\Context\Api\Admin\CreatingProductVariantContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Api/Admin/CreatingProductVariantContext.php';

        return $container->services['Sylius\\Behat\\Context\\Api\\Admin\\CreatingProductVariantContext'] = new \Sylius\Behat\Context\Api\Admin\CreatingProductVariantContext(($container->privates['sylius.behat.api_platform_client.admin'] ?? $container->load('getSylius_Behat_ApiPlatformClient_AdminService')), ($container->services['api_platform.iri_converter'] ?? $container->getApiPlatform_IriConverterService()));
    }
}
