<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChannelDataPersisterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\DataPersister\ChannelDataPersister' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\DataPersister\ChannelDataPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/DataPersister/ChannelDataPersister.php';

        return $container->services['Sylius\\Bundle\\ApiBundle\\DataPersister\\ChannelDataPersister'] = new \Sylius\Bundle\ApiBundle\DataPersister\ChannelDataPersister(($container->privates['api_platform.doctrine.orm.data_persister'] ?? $container->load('getApiPlatform_Doctrine_Orm_DataPersisterService')), ($container->services['sylius.checker.channel_deletion'] ?? $container->load('getSylius_Checker_ChannelDeletionService')));
    }
}
