<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFlysystemFilesystemAdapterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sylius\Component\Core\Filesystem\Adapter\FlysystemFilesystemAdapter' shared service.
     *
     * @return \Sylius\Component\Core\Filesystem\Adapter\FlysystemFilesystemAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Filesystem/Adapter/FilesystemAdapterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Filesystem/Adapter/FlysystemFilesystemAdapter.php';

        return $container->services['Sylius\\Component\\Core\\Filesystem\\Adapter\\FlysystemFilesystemAdapter'] = new \Sylius\Component\Core\Filesystem\Adapter\FlysystemFilesystemAdapter(($container->privates['sylius.storage'] ?? $container->load('getSylius_StorageService')));
    }
}
