<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHateoas_Configuration_MetadataDriverService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'hateoas.configuration.metadata_driver' shared service.
     *
     * @return \Metadata\Driver\DriverChain
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/jms/metadata/src/Driver/AdvancedDriverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/jms/metadata/src/Driver/DriverChain.php';

        return $container->services['hateoas.configuration.metadata_driver'] = new \Metadata\Driver\DriverChain([0 => ($container->privates['hateoas.configuration.metadata.yaml_driver'] ?? $container->load('getHateoas_Configuration_Metadata_YamlDriverService')), 1 => ($container->privates['hateoas.configuration.metadata.xml_driver'] ?? $container->load('getHateoas_Configuration_Metadata_XmlDriverService')), 2 => ($container->privates['hateoas.configuration.metadata.extension_driver'] ?? $container->load('getHateoas_Configuration_Metadata_ExtensionDriverService'))]);
    }
}
