<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIncrementPromotionUsagesListenerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\CoreBundle\EventListener\Workflow\Order\IncrementPromotionUsagesListener' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\EventListener\Workflow\Order\IncrementPromotionUsagesListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/CoreBundle/EventListener/Workflow/Order/IncrementPromotionUsagesListener.php';

        return $container->privates['Sylius\\Bundle\\CoreBundle\\EventListener\\Workflow\\Order\\IncrementPromotionUsagesListener'] = new \Sylius\Bundle\CoreBundle\EventListener\Workflow\Order\IncrementPromotionUsagesListener(($container->services['sylius.promotion_usage_modifier'] ?? $container->load('getSylius_PromotionUsageModifierService')));
    }
}
