<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLiipImagine_Factory_Config_StackService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'liip_imagine.factory.config.stack' shared service.
     *
     * @return \Liip\ImagineBundle\Factory\Config\StackFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Factory/Config/StackFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Factory/Config/StackFactory.php';

        return $container->privates['liip_imagine.factory.config.stack'] = new \Liip\ImagineBundle\Factory\Config\StackFactory();
    }
}
