<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_RetryStrategyLocatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'messenger.retry_strategy_locator' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['messenger.retry_strategy_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'catalog_promotion_removal' => ['privates', 'messenger.retry.multiplier_retry_strategy.catalog_promotion_removal', 'getMessenger_Retry_MultiplierRetryStrategy_CatalogPromotionRemovalService', true],
            'catalog_promotion_removal_failed' => ['privates', 'messenger.retry.multiplier_retry_strategy.catalog_promotion_removal_failed', 'getMessenger_Retry_MultiplierRetryStrategy_CatalogPromotionRemovalFailedService', true],
            'main' => ['privates', 'messenger.retry.multiplier_retry_strategy.main', 'getMessenger_Retry_MultiplierRetryStrategy_MainService', true],
            'main_failed' => ['privates', 'messenger.retry.multiplier_retry_strategy.main_failed', 'getMessenger_Retry_MultiplierRetryStrategy_MainFailedService', true],
        ], [
            'catalog_promotion_removal' => '?',
            'catalog_promotion_removal_failed' => '?',
            'main' => '?',
            'main_failed' => '?',
        ]);
    }
}
