<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManagingCatalogPromotionsContextService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sylius\Behat\Context\Ui\Admin\ManagingCatalogPromotionsContext' shared service.
     *
     * @return \Sylius\Behat\Context\Ui\Admin\ManagingCatalogPromotionsContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Ui/Admin/ManagingCatalogPromotionsContext.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorageInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorage.php';

        return $container->services['Sylius\\Behat\\Context\\Ui\\Admin\\ManagingCatalogPromotionsContext'] = new \Sylius\Behat\Context\Ui\Admin\ManagingCatalogPromotionsContext(($container->privates['sylius.behat.page.admin.catalog_promotion.index'] ?? $container->load('getSylius_Behat_Page_Admin_CatalogPromotion_IndexService')), ($container->privates['sylius.behat.page.admin.catalog_promotion.create'] ?? $container->load('getSylius_Behat_Page_Admin_CatalogPromotion_CreateService')), ($container->privates['sylius.behat.page.admin.catalog_promotion.update'] ?? $container->load('getSylius_Behat_Page_Admin_CatalogPromotion_UpdateService')), ($container->privates['sylius.behat.page.admin.catalog_promotion.show'] ?? $container->load('getSylius_Behat_Page_Admin_CatalogPromotion_ShowService')), ($container->privates['Sylius\\Behat\\Element\\Admin\\CatalogPromotion\\FormElement'] ?? $container->load('getFormElementService')), ($container->privates['Sylius\\Behat\\Element\\Admin\\CatalogPromotion\\FilterElement'] ?? $container->load('getFilterElementService')), ($container->privates['sylius.behat.shared_storage'] ?? ($container->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($container->privates['sylius.behat.notification_checker'] ?? $container->load('getSylius_Behat_NotificationCheckerService')));
    }
}
