<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_Redis_FactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'messenger.transport.redis.factory' shared service.
     *
     * @return \Symfony\Component\Messenger\Bridge\Redis\Transport\RedisTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/redis-messenger/Transport/RedisTransportFactory.php';

        return $container->privates['messenger.transport.redis.factory'] = new \Symfony\Component\Messenger\Bridge\Redis\Transport\RedisTransportFactory();
    }
}
