<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOutputAwareAssetsInstallerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\ThemeBundle\Asset\Installer\OutputAwareAssetsInstaller' shared service.
     *
     * @return \Sylius\Bundle\ThemeBundle\Asset\Installer\OutputAwareAssetsInstaller
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Asset/Installer/AssetsInstallerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Asset/Installer/OutputAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Asset/Installer/OutputAwareAssetsInstaller.php';

        return $container->privates['Sylius\\Bundle\\ThemeBundle\\Asset\\Installer\\OutputAwareAssetsInstaller'] = new \Sylius\Bundle\ThemeBundle\Asset\Installer\OutputAwareAssetsInstaller(($container->privates['Sylius\\Bundle\\ThemeBundle\\Asset\\Installer\\OutputAwareAssetsInstaller.inner'] ?? $container->load('getOutputAwareAssetsInstaller_InnerService')));
    }
}
