<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\CoreBundle\Doctrine\ORM\OrderRepository' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Doctrine\ORM\OrderRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Sylius\\Bundle\\CoreBundle\\Doctrine\\ORM\\OrderRepository'] = $container->get('sylius.repository.order');
    }
}
