<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOutputAwareAssetsInstaller_InnerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\ThemeBundle\Asset\Installer\OutputAwareAssetsInstaller.inner' shared service.
     *
     * @return \Sylius\Bundle\ThemeBundle\Asset\Installer\AssetsInstaller
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Asset/Installer/AssetsInstallerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Asset/Installer/AssetsInstaller.php';

        return $container->privates['Sylius\\Bundle\\ThemeBundle\\Asset\\Installer\\OutputAwareAssetsInstaller.inner'] = new \Sylius\Bundle\ThemeBundle\Asset\Installer\AssetsInstaller(($container->services['.container.private.filesystem'] ?? ($container->services['.container.private.filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), ($container->services['kernel'] ?? $container->get('kernel', 1)), ($container->privates['Sylius\\Bundle\\ThemeBundle\\Repository\\ThemeRepositoryInterface'] ?? $container->getThemeRepositoryInterfaceService()), ($container->privates['Sylius\\Bundle\\ThemeBundle\\Asset\\PathResolverInterface'] ?? $container->getPathResolverInterfaceService()), ($container->privates['Sylius\\Bundle\\ThemeBundle\\Asset\\Installer\\AssetsProviderInterface'] ?? $container->getAssetsProviderInterfaceService()));
    }
}
