<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayum_DynamicGateways_ConfigStorageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'payum.dynamic_gateways.config_storage' shared service.
     *
     * @return \Sylius\Bundle\PayumBundle\Storage\DoctrineStorage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Storage/StorageInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Storage/AbstractStorage.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/PayumBundle/Storage/DoctrineStorage.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->services['payum.dynamic_gateways.config_storage'])) {
            return $container->services['payum.dynamic_gateways.config_storage'];
        }

        return $container->services['payum.dynamic_gateways.config_storage'] = new \Sylius\Bundle\PayumBundle\Storage\DoctrineStorage($a, 'Sylius\\Bundle\\PayumBundle\\Model\\GatewayConfig');
    }
}
