<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayum_TokenFactoryBuilderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'payum.token_factory_builder' shared service.
     *
     * @return \Payum\Core\Bridge\Symfony\Builder\TokenFactoryBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Bridge/Symfony/Builder/TokenFactoryBuilder.php';

        $a = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->privates['payum.token_factory_builder'])) {
            return $container->privates['payum.token_factory_builder'];
        }

        return $container->privates['payum.token_factory_builder'] = new \Payum\Core\Bridge\Symfony\Builder\TokenFactoryBuilder($a);
    }
}
