<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPositionerInterfaceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sylius\Component\Core\Positioner\PositionerInterface' shared service.
     *
     * @return \Sylius\Component\Core\Positioner\Positioner
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Positioner/PositionerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Positioner/Positioner.php';

        return $container->services['Sylius\\Component\\Core\\Positioner\\PositionerInterface'] = new \Sylius\Component\Core\Positioner\Positioner();
    }
}
