<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPriceHistoryContextService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sylius\Behat\Context\Setup\PriceHistoryContext' shared service.
     *
     * @return \Sylius\Behat\Context\Setup\PriceHistoryContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Setup/PriceHistoryContext.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/calendar/tests/Behat/Context/Setup/CalendarContext.php';

        return $container->services['Sylius\\Behat\\Context\\Setup\\PriceHistoryContext'] = new \Sylius\Behat\Context\Setup\PriceHistoryContext(($container->services['Sylius\\Calendar\\Tests\\Behat\\Context\\Setup\\CalendarContext'] ?? ($container->services['Sylius\\Calendar\\Tests\\Behat\\Context\\Setup\\CalendarContext'] = new \Sylius\Calendar\Tests\Behat\Context\Setup\CalendarContext(\dirname(__DIR__, 4)))), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['Sylius\\Component\\Product\\Resolver\\ProductVariantResolverInterface'] ?? $container->getProductVariantResolverInterfaceService()));
    }
}
