<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionCouponGeneratorInstructionFactoryInterfaceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sylius\Component\Promotion\Factory\PromotionCouponGeneratorInstructionFactoryInterface' shared service.
     *
     * @return \Sylius\Component\Promotion\Factory\PromotionCouponGeneratorInstructionFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Promotion/Factory/PromotionCouponGeneratorInstructionFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Promotion/Factory/PromotionCouponGeneratorInstructionFactory.php';

        return $container->services['Sylius\\Component\\Promotion\\Factory\\PromotionCouponGeneratorInstructionFactoryInterface'] = new \Sylius\Component\Promotion\Factory\PromotionCouponGeneratorInstructionFactory();
    }
}
