<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResendShipmentConfirmationEmailActionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\AdminBundle\Action\ResendShipmentConfirmationEmailAction' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\Action\ResendShipmentConfirmationEmailAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/AdminBundle/Action/ResendShipmentConfirmationEmailAction.php';

        return $container->services['Sylius\\Bundle\\AdminBundle\\Action\\ResendShipmentConfirmationEmailAction'] = new \Sylius\Bundle\AdminBundle\Action\ResendShipmentConfirmationEmailAction(($container->services['sylius.repository.shipment'] ?? $container->getSylius_Repository_ShipmentService()), ($container->services['sylius.email_manager.shipment'] ?? $container->load('getSylius_EmailManager_ShipmentService')), ($container->services['.container.private.security.csrf.token_manager'] ?? $container->load('get_Container_Private_Security_Csrf_TokenManagerService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
