<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Config_NewApiShopUserService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.config.new_api_shop_user' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

        return $container->privates['security.firewall.map.config.new_api_shop_user'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('new_api_shop_user', 'security.user_checker', '.security.request_matcher.KeFX2AP', true, true, 'sylius.shop_user_provider.email_or_name_based', NULL, 'security.authenticator.jwt.new_api_shop_user', NULL, NULL, [0 => 'jwt', 1 => 'json_login'], NULL);
    }
}
