<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Factory_DefaultChannelService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.factory.default_channel' shared service.
     *
     * @return \Sylius\Component\Core\Test\Services\DefaultChannelFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Test/Services/DefaultChannelFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Test/Services/DefaultChannelFactory.php';

        return $container->services['sylius.behat.factory.default_channel'] = new \Sylius\Component\Core\Test\Services\DefaultChannelFactory(($container->services['Sylius\\Component\\Channel\\Factory\\ChannelFactoryInterface'] ?? $container->load('getChannelFactoryInterfaceService')), ($container->services['sylius.factory.currency'] ?? ($container->services['sylius.factory.currency'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Currency\\Model\\Currency'))), ($container->services['sylius.factory.locale'] ?? ($container->services['sylius.factory.locale'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Locale\\Model\\Locale'))), ($container->services['sylius.repository.channel'] ?? $container->getSylius_Repository_ChannelService()), ($container->services['sylius.repository.currency'] ?? $container->load('getSylius_Repository_CurrencyService')), ($container->services['sylius.repository.locale'] ?? $container->getSylius_Repository_LocaleService()), 'en_US');
    }
}
