<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_MessageSendCacherService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.message_send_cacher' shared service.
     *
     * @return \Sylius\Behat\Service\MessageSendCacher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/MessageSendCacher.php';

        return $container->services['sylius.behat.message_send_cacher'] = new \Sylius\Behat\Service\MessageSendCacher(($container->privates['test.mailer_pool'] ?? $container->getTest_MailerPoolService()));
    }
}
