<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Ui_Admin_ProductShowpageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.ui.admin.product_showpage' shared service.
     *
     * @return \Sylius\Behat\Context\Ui\Admin\ProductShowPageContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Ui/Admin/ProductShowPageContext.php';

        return $container->services['sylius.behat.context.ui.admin.product_showpage'] = new \Sylius\Behat\Context\Ui\Admin\ProductShowPageContext(($container->privates['sylius.behat.page.admin.product.index'] ?? $container->load('getSylius_Behat_Page_Admin_Product_IndexService')), ($container->privates['sylius.behat.page.admin.product.show_page'] ?? $container->load('getSylius_Behat_Page_Admin_Product_ShowPageService')), ($container->privates['sylius.behat.element.product.show.associations'] ?? $container->load('getSylius_Behat_Element_Product_Show_AssociationsService')), ($container->privates['sylius.behat.element.product.show.attributes'] ?? $container->load('getSylius_Behat_Element_Product_Show_AttributesService')), ($container->privates['sylius.behat.element.product.show.details'] ?? $container->load('getSylius_Behat_Element_Product_Show_DetailsService')), ($container->privates['sylius.behat.element.product.show.media'] ?? $container->load('getSylius_Behat_Element_Product_Show_MediaService')), ($container->privates['sylius.behat.element.product.show.more_details'] ?? $container->load('getSylius_Behat_Element_Product_Show_MoreDetailsService')), ($container->privates['sylius.behat.element.product.show.pricing'] ?? $container->load('getSylius_Behat_Element_Product_Show_PricingService')), ($container->privates['sylius.behat.element.product.show.shipping'] ?? $container->load('getSylius_Behat_Element_Product_Show_ShippingService')), ($container->privates['sylius.behat.element.product.show.taxonomy'] ?? $container->load('getSylius_Behat_Element_Product_Show_TaxonomyService')), ($container->privates['sylius.behat.element.product.show.options'] ?? $container->load('getSylius_Behat_Element_Product_Show_OptionsService')), ($container->privates['sylius.behat.element.product.show.variants'] ?? $container->load('getSylius_Behat_Element_Product_Show_VariantsService')), ($container->services['router'] ?? $container->getRouterService()));
    }
}
