<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authenticator_JsonLogin_NewApiAdminUserService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'security.authenticator.json_login.new_api_admin_user' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\JsonLoginAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/InteractiveAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/JsonLoginAuthenticator.php';

        $a = ($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService'));

        if (isset($container->privates['security.authenticator.json_login.new_api_admin_user'])) {
            return $container->privates['security.authenticator.json_login.new_api_admin_user'];
        }
        $b = ($container->privates['security.authentication.success_handler.new_api_admin_user.json_login'] ?? $container->load('getSecurity_Authentication_SuccessHandler_NewApiAdminUser_JsonLoginService'));

        if (isset($container->privates['security.authenticator.json_login.new_api_admin_user'])) {
            return $container->privates['security.authenticator.json_login.new_api_admin_user'];
        }
        $c = ($container->privates['security.authentication.failure_handler.new_api_admin_user.json_login'] ?? $container->load('getSecurity_Authentication_FailureHandler_NewApiAdminUser_JsonLoginService'));

        if (isset($container->privates['security.authenticator.json_login.new_api_admin_user'])) {
            return $container->privates['security.authenticator.json_login.new_api_admin_user'];
        }

        $container->privates['security.authenticator.json_login.new_api_admin_user'] = $instance = new \Symfony\Component\Security\Http\Authenticator\JsonLoginAuthenticator($a, ($container->privates['sylius.admin_user_provider.email_or_name_based'] ?? $container->load('getSylius_AdminUserProvider_EmailOrNameBasedService')), $b, $c, ['check_path' => '/api/v2/admin/authentication-token', 'username_path' => 'email', 'password_path' => 'password', 'use_forward' => false, 'require_previous_session' => false, 'login_path' => '/login'], ($container->privates['property_accessor'] ?? $container->getPropertyAccessorService()));

        if ($container->has('translator')) {
            $instance->setTranslator(($container->services['translator'] ?? $container->getTranslatorService()));
        }

        return $instance;
    }
}
