<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Setup_ChannelService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.setup.channel' shared service.
     *
     * @return \Sylius\Behat\Context\Setup\ChannelContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Setup/ChannelContext.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorageInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorage.php';

        return $container->services['sylius.behat.context.setup.channel'] = new \Sylius\Behat\Context\Setup\ChannelContext(($container->privates['sylius.behat.shared_storage'] ?? ($container->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($container->privates['sylius.behat.channel_context_setter'] ?? $container->load('getSylius_Behat_ChannelContextSetterService')), ($container->services['sylius.behat.factory.default_united_states_channel'] ?? $container->load('getSylius_Behat_Factory_DefaultUnitedStatesChannelService')), ($container->services['sylius.behat.factory.default_channel'] ?? $container->load('getSylius_Behat_Factory_DefaultChannelService')), ($container->services['sylius.repository.channel'] ?? $container->getSylius_Repository_ChannelService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
