<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Setup_ZoneService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.setup.zone' shared service.
     *
     * @return \Sylius\Behat\Context\Setup\ZoneContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Setup/ZoneContext.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorageInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorage.php';

        return $container->services['sylius.behat.context.setup.zone'] = new \Sylius\Behat\Context\Setup\ZoneContext(($container->privates['sylius.behat.shared_storage'] ?? ($container->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($container->services['sylius.repository.zone'] ?? $container->getSylius_Repository_ZoneService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['Sylius\\Component\\Addressing\\Factory\\ZoneFactoryInterface'] ?? $container->load('getZoneFactoryInterfaceService')), ($container->services['sylius.factory.zone_member'] ?? ($container->services['sylius.factory.zone_member'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Addressing\\Model\\ZoneMember'))));
    }
}
