<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_TableAccessorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.behat.table_accessor' shared service.
     *
     * @return \Sylius\Behat\Service\Accessor\TableAccessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/Accessor/TableAccessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/Accessor/TableAccessor.php';

        return $container->privates['sylius.behat.table_accessor'] = new \Sylius\Behat\Service\Accessor\TableAccessor();
    }
}
