<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Hook_MailerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.hook.mailer' shared service.
     *
     * @return \Sylius\Behat\Context\Hook\MailerContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Hook/MailerContext.php';

        return $container->services['sylius.behat.context.hook.mailer'] = new \Sylius\Behat\Context\Hook\MailerContext(($container->privates['test.mailer_pool'] ?? $container->getTest_MailerPoolService()));
    }
}
