<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_CookieSetterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.behat.cookie_setter' shared service.
     *
     * @return \Sylius\Behat\Service\Setter\CookieSetter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/Setter/CookieSetterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/Setter/CookieSetter.php';

        return $container->privates['sylius.behat.cookie_setter'] = new \Sylius\Behat\Service\Setter\CookieSetter(($container->services['behat.mink.default_session'] ?? $container->load('getBehat_Mink_DefaultSessionService')), ($container->services['behat.mink.parameters'] ?? $container->load('getBehat_Mink_ParametersService')));
    }
}
