<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_StorageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.storage' shared service.
     *
     * @return \League\Flysystem\Filesystem
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/FilesystemReader.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/FilesystemWriter.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/FilesystemOperator.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/CalculateChecksumFromStream.php';
        include_once \dirname(__DIR__, 4).'/vendor/league/flysystem/src/Filesystem.php';

        return $container->privates['sylius.storage'] = new \League\Flysystem\Filesystem(($container->privates['flysystem.adapter.sylius.storage'] ?? $container->load('getFlysystem_Adapter_Sylius_StorageService')), ['visibility' => NULL, 'directory_visibility' => NULL, 'case_sensitive' => true, 'disable_asserts' => false]);
    }
}
