<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Ui_Admin_ManagingAdministratorsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.ui.admin.managing_administrators' shared service.
     *
     * @return \Sylius\Behat\Context\Ui\Admin\ManagingAdministratorsContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Ui/Admin/ManagingAdministratorsContext.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorageInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorage.php';

        return $container->services['sylius.behat.context.ui.admin.managing_administrators'] = new \Sylius\Behat\Context\Ui\Admin\ManagingAdministratorsContext(($container->privates['sylius.behat.page.admin.administrator.create'] ?? $container->load('getSylius_Behat_Page_Admin_Administrator_CreateService')), ($container->privates['sylius.behat.page.admin.administrator.index'] ?? $container->load('getSylius_Behat_Page_Admin_Administrator_IndexService')), ($container->privates['sylius.behat.page.admin.administrator.update'] ?? $container->load('getSylius_Behat_Page_Admin_Administrator_UpdateService')), ($container->privates['sylius.behat.element.admin.top_bar'] ?? $container->load('getSylius_Behat_Element_Admin_TopBarService')), ($container->privates['sylius.behat.notification_checker'] ?? $container->load('getSylius_Behat_NotificationCheckerService')), ($container->services['sylius.repository.admin_user'] ?? $container->load('getSylius_Repository_AdminUserService')), ($container->privates['sylius.behat.shared_storage'] ?? ($container->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())));
    }
}
