<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Ui_Shop_CartService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.ui.shop.cart' shared service.
     *
     * @return \Sylius\Behat\Context\Ui\Shop\CartContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Ui/Shop/CartContext.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorageInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorage.php';

        return $container->services['sylius.behat.context.ui.shop.cart'] = new \Sylius\Behat\Context\Ui\Shop\CartContext(($container->privates['sylius.behat.shared_storage'] ?? ($container->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($container->privates['sylius.behat.page.shop.cart_summary'] ?? $container->load('getSylius_Behat_Page_Shop_CartSummaryService')), ($container->privates['sylius.behat.page.shop.checkout.address'] ?? $container->load('getSylius_Behat_Page_Shop_Checkout_AddressService')), ($container->privates['Sylius\\Behat\\Element\\Shop\\CheckoutSubtotalElementInterface'] ?? $container->load('getCheckoutSubtotalElementInterfaceService')), ($container->privates['sylius.behat.page.shop.product.show'] ?? $container->load('getSylius_Behat_Page_Shop_Product_ShowService')), ($container->privates['Sylius\\Behat\\Element\\Shop\\CartWidgetElementInterface'] ?? $container->load('getCartWidgetElementInterfaceService')), ($container->privates['sylius.behat.notification_checker'] ?? $container->load('getSylius_Behat_NotificationCheckerService')), ($container->privates['Sylius\\Behat\\Service\\SessionManagerInterface'] ?? $container->load('getSessionManagerInterfaceService')), ($container->privates['sylius.behat.element.browser'] ?? $container->load('getSylius_Behat_Element_BrowserService')));
    }
}
