<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_ResponseLoaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.behat.response_loader' shared service.
     *
     * @return \Sylius\Behat\Service\ResponseLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/ResponseLoaderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/ResponseLoader.php';

        return $container->privates['sylius.behat.response_loader'] = new \Sylius\Behat\Service\ResponseLoader();
    }
}
