<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Transform_AddressService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.transform.address' shared service.
     *
     * @return \Sylius\Behat\Context\Transform\AddressContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Transform/AddressContext.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Addressing/Converter/CountryNameConverterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Addressing/Converter/CountryNameConverter.php';

        return $container->services['sylius.behat.context.transform.address'] = new \Sylius\Behat\Context\Transform\AddressContext(($container->services['sylius.factory.address'] ?? $container->load('getSylius_Factory_AddressService')), ($container->services['sylius.converter.country_name'] ?? ($container->services['sylius.converter.country_name'] = new \Sylius\Component\Addressing\Converter\CountryNameConverter())), ($container->services['sylius.repository.address'] ?? $container->load('getSylius_Repository_AddressService')), ($container->services['sylius.fixture.example_factory.address'] ?? $container->load('getSylius_Fixture_ExampleFactory_AddressService')));
    }
}
