<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Api_Admin_ResettingPasswordService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.api.admin.resetting_password' shared service.
     *
     * @return \Sylius\Behat\Context\Api\Admin\ResettingPasswordContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Api/Admin/ResettingPasswordContext.php';

        return $container->services['sylius.behat.context.api.admin.resetting_password'] = new \Sylius\Behat\Context\Api\Admin\ResettingPasswordContext(($container->privates['sylius.behat.api_platform_client.shop'] ?? $container->load('getSylius_Behat_ApiPlatformClient_ShopService')), ($container->privates['sylius.behat.request_factory'] ?? $container->load('getSylius_Behat_RequestFactoryService')), ($container->privates['Sylius\\Behat\\Client\\ResponseCheckerInterface'] ?? $container->load('getResponseCheckerInterfaceService')), '/api/v2');
    }
}
