<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Setup_ProductAssociationService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.setup.product_association' shared service.
     *
     * @return \Sylius\Behat\Context\Setup\ProductAssociationContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Setup/ProductAssociationContext.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorageInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorage.php';

        return $container->services['sylius.behat.context.setup.product_association'] = new \Sylius\Behat\Context\Setup\ProductAssociationContext(($container->privates['sylius.behat.shared_storage'] ?? ($container->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($container->services['sylius.factory.product_association_type'] ?? $container->load('getSylius_Factory_ProductAssociationTypeService')), ($container->services['sylius.factory.product_association_type_translation'] ?? ($container->services['sylius.factory.product_association_type_translation'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Product\\Model\\ProductAssociationTypeTranslation'))), ($container->services['sylius.factory.product_association'] ?? ($container->services['sylius.factory.product_association'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Product\\Model\\ProductAssociation'))), ($container->services['sylius.repository.product_association_type'] ?? $container->load('getSylius_Repository_ProductAssociationTypeService')), ($container->services['sylius.repository.product_association'] ?? $container->load('getSylius_Repository_ProductAssociationService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
