<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Ui_Admin_ResettingPasswordService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.ui.admin.resetting_password' shared service.
     *
     * @return \Sylius\Behat\Context\Ui\Admin\ResettingPasswordContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Ui/Admin/ResettingPasswordContext.php';

        return $container->services['sylius.behat.context.ui.admin.resetting_password'] = new \Sylius\Behat\Context\Ui\Admin\ResettingPasswordContext(($container->privates['sylius.behat.page.admin.request_password_reset'] ?? $container->load('getSylius_Behat_Page_Admin_RequestPasswordResetService')), ($container->privates['sylius.behat.page.admin.reset_password'] ?? $container->load('getSylius_Behat_Page_Admin_ResetPasswordService')), ($container->privates['sylius.behat.element.admin.account.reset'] ?? $container->load('getSylius_Behat_Element_Admin_Account_ResetService')), ($container->privates['sylius.behat.notification_checker'] ?? $container->load('getSylius_Behat_NotificationCheckerService')));
    }
}
