<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Ui_Admin_ManagingProductReviewsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.ui.admin.managing_product_reviews' shared service.
     *
     * @return \Sylius\Behat\Context\Ui\Admin\ManagingProductReviewsContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Ui/Admin/ManagingProductReviewsContext.php';

        return $container->services['sylius.behat.context.ui.admin.managing_product_reviews'] = new \Sylius\Behat\Context\Ui\Admin\ManagingProductReviewsContext(($container->privates['sylius.behat.page.admin.product_review.index'] ?? $container->load('getSylius_Behat_Page_Admin_ProductReview_IndexService')), ($container->privates['sylius.behat.page.admin.product_review.update'] ?? $container->load('getSylius_Behat_Page_Admin_ProductReview_UpdateService')), ($container->privates['sylius.behat.notification_checker'] ?? $container->load('getSylius_Behat_NotificationCheckerService')));
    }
}
