<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Ui_Shop_LoginService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.ui.shop.login' shared service.
     *
     * @return \Sylius\Behat\Context\Ui\Shop\LoginContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Ui/Shop/LoginContext.php';

        return $container->services['sylius.behat.context.ui.shop.login'] = new \Sylius\Behat\Context\Ui\Shop\LoginContext(($container->privates['sylius.behat.page.shop.home'] ?? $container->load('getSylius_Behat_Page_Shop_HomeService')), ($container->privates['sylius.behat.page.shop.account.login'] ?? $container->load('getSylius_Behat_Page_Shop_Account_LoginService')), ($container->privates['sylius.behat.page.shop.account.register'] ?? $container->load('getSylius_Behat_Page_Shop_Account_RegisterService')), ($container->privates['sylius.behat.page.shop.account.request_password_reset'] ?? $container->load('getSylius_Behat_Page_Shop_Account_RequestPasswordResetService')), ($container->privates['sylius.behat.page.shop.account.reset_password'] ?? $container->load('getSylius_Behat_Page_Shop_Account_ResetPasswordService')), ($container->privates['sylius.behat.page.shop.account.well_known_password_change'] ?? $container->load('getSylius_Behat_Page_Shop_Account_WellKnownPasswordChangeService')), ($container->privates['sylius.behat.element.shop.account.register'] ?? $container->load('getSylius_Behat_Element_Shop_Account_RegisterService')), ($container->privates['sylius.behat.notification_checker'] ?? $container->load('getSylius_Behat_NotificationCheckerService')), ($container->privates['sylius.behat.current_page_resolver'] ?? $container->load('getSylius_Behat_CurrentPageResolverService')));
    }
}
