<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Config_ShopService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.config.shop' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

        return $container->privates['security.firewall.map.config.shop'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('shop', 'security.user_checker', '.security.request_matcher.O0SiwbV', true, false, 'sylius.shop_user_provider.email_or_name_based', 'shop', 'security.authenticator.form_login.shop', NULL, NULL, [0 => 'switch_user', 1 => 'form_login', 2 => 'remember_me'], ['role' => 'ROLE_ALLOWED_TO_SWITCH', 'parameter' => '_switch_user']);
    }
}
