<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Api_Shop_HomepageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.api.shop.homepage' shared service.
     *
     * @return \Sylius\Behat\Context\Api\Shop\HomepageContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Api/Shop/HomepageContext.php';

        return $container->services['sylius.behat.context.api.shop.homepage'] = new \Sylius\Behat\Context\Api\Shop\HomepageContext(($container->privates['sylius.behat.api_platform_client.shop'] ?? $container->load('getSylius_Behat_ApiPlatformClient_ShopService')), ($container->privates['Sylius\\Behat\\Client\\ResponseCheckerInterface'] ?? $container->load('getResponseCheckerInterfaceService')), ($container->services['api_platform.iri_converter'] ?? $container->getApiPlatform_IriConverterService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), '/api/v2');
    }
}
