<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Promotion_EligibilityChecker_PromotionCouponPerCustomerUsageLimitService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.promotion.eligibility_checker.promotion_coupon_per_customer_usage_limit' shared service.
     *
     * @return \Sylius\Component\Core\Promotion\Checker\Eligibility\PromotionCouponPerCustomerUsageLimitEligibilityChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Promotion/Checker/Eligibility/PromotionCouponEligibilityCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Promotion/Checker/Eligibility/PromotionCouponPerCustomerUsageLimitEligibilityChecker.php';

        return $container->privates['sylius.promotion.eligibility_checker.promotion_coupon_per_customer_usage_limit'] = new \Sylius\Component\Core\Promotion\Checker\Eligibility\PromotionCouponPerCustomerUsageLimitEligibilityChecker(($container->services['sylius.repository.order'] ?? $container->getSylius_Repository_OrderService()));
    }
}
