<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Ui_PaypalService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.ui.paypal' shared service.
     *
     * @return \Sylius\Behat\Context\Ui\PaypalContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Ui/PaypalContext.php';

        return $container->services['sylius.behat.context.ui.paypal'] = new \Sylius\Behat\Context\Ui\PaypalContext(($container->privates['sylius.behat.page.external.paypal_checkout_express'] ?? $container->load('getSylius_Behat_Page_External_PaypalCheckoutExpressService')), ($container->privates['sylius.behat.page.shop.order.show'] ?? $container->load('getSylius_Behat_Page_Shop_Order_ShowService')), ($container->privates['sylius.behat.page.shop.checkout.complete'] ?? $container->load('getSylius_Behat_Page_Shop_Checkout_CompleteService')), ($container->privates['sylius.behat.paypal_api_mocker'] ?? $container->load('getSylius_Behat_PaypalApiMockerService')));
    }
}
