<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_NotificationCheckerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.behat.notification_checker' shared service.
     *
     * @return \Sylius\Behat\Service\NotificationChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/NotificationCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/NotificationChecker.php';

        return $container->privates['sylius.behat.notification_checker'] = new \Sylius\Behat\Service\NotificationChecker(($container->privates['sylius.behat.notification_accessor'] ?? $container->load('getSylius_Behat_NotificationAccessorService')));
    }
}
