<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_PromotionRuleUpdater_HasTaxonService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.promotion_rule_updater.has_taxon' shared service.
     *
     * @return \Sylius\Component\Core\Promotion\Updater\Rule\HasTaxonRuleUpdater
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Promotion/Updater/Rule/TaxonAwareRuleUpdaterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Promotion/Updater/Rule/HasTaxonRuleUpdater.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->services['sylius.promotion_rule_updater.has_taxon'])) {
            return $container->services['sylius.promotion_rule_updater.has_taxon'];
        }

        return $container->services['sylius.promotion_rule_updater.has_taxon'] = new \Sylius\Component\Core\Promotion\Updater\Rule\HasTaxonRuleUpdater(($container->services['sylius.repository.promotion_rule'] ?? $container->load('getSylius_Repository_PromotionRuleService')), $a);
    }
}
