<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_QueryBus_Messenger_HandlersLocatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.query_bus.messenger.handlers_locator' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlersLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        return $container->privates['sylius.query_bus.messenger.handlers_locator'] = new \Symfony\Component\Messenger\Handler\HandlersLocator(['Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.tPnoIpG'] ?? $container->load('get_Messenger_HandlerDescriptor_TPnoIpGService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Query\\GetCustomerStatistics' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.E_4QOgy'] ?? $container->load('get_Messenger_HandlerDescriptor_E4QOgyService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Query\\GetAddressLogEntryCollection' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.e._X57L'] ?? $container->load('get_Messenger_HandlerDescriptor_E_X57LService'));
        }, 1)]);
    }
}
