<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Ui_Admin_ManagingProductOptionsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.ui.admin.managing_product_options' shared service.
     *
     * @return \Sylius\Behat\Context\Ui\Admin\ManagingProductOptionsContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Ui/Admin/ManagingProductOptionsContext.php';

        return $container->services['sylius.behat.context.ui.admin.managing_product_options'] = new \Sylius\Behat\Context\Ui\Admin\ManagingProductOptionsContext(($container->privates['sylius.behat.page.admin.product_option.index'] ?? $container->load('getSylius_Behat_Page_Admin_ProductOption_IndexService')), ($container->privates['sylius.behat.page.admin.product_option.create'] ?? $container->load('getSylius_Behat_Page_Admin_ProductOption_CreateService')), ($container->privates['sylius.behat.page.admin.product_option.update'] ?? $container->load('getSylius_Behat_Page_Admin_ProductOption_UpdateService')), ($container->privates['sylius.behat.current_page_resolver'] ?? $container->load('getSylius_Behat_CurrentPageResolverService')));
    }
}
