<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Ui_Admin_MoveToEditProductPageService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.ui.admin.move_to_edit_product_page' shared service.
     *
     * @return \Sylius\Behat\Context\Ui\Admin\AccessingEditPageFromProductShowPageContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Ui/Admin/AccessingEditPageFromProductShowPageContext.php';

        return $container->services['sylius.behat.context.ui.admin.move_to_edit_product_page'] = new \Sylius\Behat\Context\Ui\Admin\AccessingEditPageFromProductShowPageContext(($container->privates['sylius.behat.page.admin.product.update_simple'] ?? $container->load('getSylius_Behat_Page_Admin_Product_UpdateSimpleService')), ($container->privates['sylius.behat.page.admin.product_variant.update'] ?? $container->load('getSylius_Behat_Page_Admin_ProductVariant_UpdateService')));
    }
}
