<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_PromotionSubjectCouponEligibilityCheckerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.promotion_subject_coupon_eligibility_checker' shared service.
     *
     * @return \Sylius\Component\Promotion\Checker\Eligibility\PromotionSubjectCouponEligibilityChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Promotion/Checker/Eligibility/PromotionEligibilityCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Promotion/Checker/Eligibility/PromotionSubjectCouponEligibilityChecker.php';

        return $container->privates['sylius.promotion_subject_coupon_eligibility_checker'] = new \Sylius\Component\Promotion\Checker\Eligibility\PromotionSubjectCouponEligibilityChecker(($container->services['sylius.promotion_coupon_eligibility_checker'] ?? $container->load('getSylius_PromotionCouponEligibilityCheckerService')));
    }
}
