<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Domain_ManagingShippingMethodsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.domain.managing_shipping_methods' shared service.
     *
     * @return \Sylius\Behat\Context\Domain\ManagingShippingMethodsContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Domain/ManagingShippingMethodsContext.php';

        return $container->services['sylius.behat.context.domain.managing_shipping_methods'] = new \Sylius\Behat\Context\Domain\ManagingShippingMethodsContext(($container->services['sylius.repository.shipping_method'] ?? $container->getSylius_Repository_ShippingMethodService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
