<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Domain_ManagingPaymentsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.domain.managing_payments' shared service.
     *
     * @return \Sylius\Behat\Context\Domain\ManagingPaymentsContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Domain/ManagingPaymentsContext.php';

        return $container->services['sylius.behat.context.domain.managing_payments'] = new \Sylius\Behat\Context\Domain\ManagingPaymentsContext(($container->services['sylius.repository.payment'] ?? $container->load('getSylius_Repository_PaymentService')));
    }
}
