<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authenticator_FormLogin_ShopService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'security.authenticator.form_login.shop' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\FormLoginAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AbstractAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/InteractiveAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AbstractLoginFormAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/FormLoginAuthenticator.php';

        $a = ($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService'));

        if (isset($container->privates['security.authenticator.form_login.shop'])) {
            return $container->privates['security.authenticator.form_login.shop'];
        }
        $b = ($container->privates['security.authentication.success_handler.shop.form_login'] ?? $container->load('getSecurity_Authentication_SuccessHandler_Shop_FormLoginService'));

        if (isset($container->privates['security.authenticator.form_login.shop'])) {
            return $container->privates['security.authenticator.form_login.shop'];
        }
        $c = ($container->privates['security.authentication.failure_handler.shop.form_login'] ?? $container->load('getSecurity_Authentication_FailureHandler_Shop_FormLoginService'));

        if (isset($container->privates['security.authenticator.form_login.shop'])) {
            return $container->privates['security.authenticator.form_login.shop'];
        }

        return $container->privates['security.authenticator.form_login.shop'] = new \Symfony\Component\Security\Http\Authenticator\FormLoginAuthenticator($a, ($container->privates['sylius.shop_user_provider.email_or_name_based'] ?? $container->load('getSylius_ShopUserProvider_EmailOrNameBasedService')), $b, $c, ['login_path' => 'sylius_shop_login', 'check_path' => 'sylius_shop_login_check', 'use_forward' => false, 'enable_csrf' => true, 'csrf_parameter' => '_csrf_shop_security_token', 'csrf_token_id' => 'shop_authenticate', 'require_previous_session' => false, 'username_parameter' => '_username', 'password_parameter' => '_password', 'post_only' => true, 'form_only' => false]);
    }
}
