<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_PromotionRulesEligibilityCheckerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sylius.promotion_rules_eligibility_checker' shared service.
     *
     * @return \Sylius\Component\Promotion\Checker\Eligibility\PromotionRulesEligibilityChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Promotion/Checker/Eligibility/PromotionEligibilityCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Promotion/Checker/Eligibility/PromotionRulesEligibilityChecker.php';

        $a = ($container->services['sylius.registry_promotion_rule_checker'] ?? $container->load('getSylius_RegistryPromotionRuleCheckerService'));

        if (isset($container->privates['sylius.promotion_rules_eligibility_checker'])) {
            return $container->privates['sylius.promotion_rules_eligibility_checker'];
        }

        return $container->privates['sylius.promotion_rules_eligibility_checker'] = new \Sylius\Component\Promotion\Checker\Eligibility\PromotionRulesEligibilityChecker($a);
    }
}
