<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Repository_TaxonService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.repository.taxon' shared service.
     *
     * @return \Sylius\Bundle\TaxonomyBundle\Doctrine\ORM\TaxonRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Taxonomy/Repository/TaxonRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/TaxonomyBundle/Doctrine/ORM/TaxonRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->services['sylius.repository.taxon'])) {
            return $container->services['sylius.repository.taxon'];
        }

        return $container->services['sylius.repository.taxon'] = new \Sylius\Bundle\TaxonomyBundle\Doctrine\ORM\TaxonRepository($a, $a->getClassMetadata('Sylius\\Component\\Core\\Model\\Taxon'));
    }
}
