<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Behat_Context_Ui_Shop_Checkout_AddressingService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.behat.context.ui.shop.checkout.addressing' shared service.
     *
     * @return \Sylius\Behat\Context\Ui\Shop\Checkout\CheckoutAddressingContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorageInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/SharedStorage.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Addressing/Comparator/AddressComparatorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Addressing/Comparator/AddressComparator.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/Helper/JavaScriptTestHelperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Behat/Service/Helper/JavaScriptTestHelper.php';

        return $container->services['sylius.behat.context.ui.shop.checkout.addressing'] = new \Sylius\Behat\Context\Ui\Shop\Checkout\CheckoutAddressingContext(($container->privates['sylius.behat.shared_storage'] ?? ($container->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($container->privates['sylius.behat.page.shop.checkout.address'] ?? $container->load('getSylius_Behat_Page_Shop_Checkout_AddressService')), ($container->services['sylius.factory.address'] ?? $container->load('getSylius_Factory_AddressService')), ($container->services['sylius.address_comparator'] ?? ($container->services['sylius.address_comparator'] = new \Sylius\Component\Addressing\Comparator\AddressComparator())), ($container->privates['sylius.behat.page.shop.checkout.select_shipping'] ?? $container->load('getSylius_Behat_Page_Shop_Checkout_SelectShippingService')), ($container->services['sylius.behat.java_script_test_helper'] ?? ($container->services['sylius.behat.java_script_test_helper'] = new \Sylius\Behat\Service\Helper\JavaScriptTestHelper(1000000, 7))));
    }
}
