<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_OrderPaymentProviderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sylius.order_payment_provider' shared service.
     *
     * @return \Sylius\Component\Core\Payment\Provider\OrderPaymentProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Payment/Provider/OrderPaymentProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Payment/Provider/OrderPaymentProvider.php';

        $a = ($container->services['sylius.payment_method_resolver.default'] ?? $container->load('getSylius_PaymentMethodResolver_DefaultService'));

        if (isset($container->services['sylius.order_payment_provider'])) {
            return $container->services['sylius.order_payment_provider'];
        }
        $b = ($container->services['SM\\Factory\\FactoryInterface'] ?? $container->getFactoryInterfaceService());

        if (isset($container->services['sylius.order_payment_provider'])) {
            return $container->services['sylius.order_payment_provider'];
        }

        return $container->services['sylius.order_payment_provider'] = new \Sylius\Component\Core\Payment\Provider\OrderPaymentProvider($a, ($container->services['Sylius\\Component\\Payment\\Factory\\PaymentFactoryInterface'] ?? $container->load('getPaymentFactoryInterfaceService')), $b);
    }
}
