<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserImpersonatorInterfaceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\CoreBundle\Security\UserImpersonatorInterface' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Security\UserImpersonator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/CoreBundle/Security/UserImpersonatorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/CoreBundle/Security/UserImpersonator.php';

        return $container->services['Sylius\\Bundle\\CoreBundle\\Security\\UserImpersonatorInterface'] = new \Sylius\Bundle\CoreBundle\Security\UserImpersonator(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), 'shop', ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
