<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadTaxonImageActionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\Controller\UploadTaxonImageAction' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Controller\UploadTaxonImageAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/Controller/UploadTaxonImageAction.php';

        return $container->services['Sylius\\Bundle\\ApiBundle\\Controller\\UploadTaxonImageAction'] = new \Sylius\Bundle\ApiBundle\Controller\UploadTaxonImageAction(($container->privates['Sylius\\Bundle\\ApiBundle\\Creator\\TaxonImageCreator'] ?? $container->load('getTaxonImageCreatorService')));
    }
}
