<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_AJ3te7TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.aJ3te7T' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/InformAboutCartRecalculationHandler.php';

        return $container->privates['.messenger.handler_descriptor.aJ3te7T'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->services['Sylius\\Bundle\\ApiBundle\\CommandHandler\\Cart\\InformAboutCartRecalculationHandler'] ?? ($container->services['Sylius\\Bundle\\ApiBundle\\CommandHandler\\Cart\\InformAboutCartRecalculationHandler'] = new \Sylius\Bundle\ApiBundle\CommandHandler\Cart\InformAboutCartRecalculationHandler())), ['bus' => 'sylius.command_bus']);
    }
}
