<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssignShippingDateListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\CoreBundle\EventListener\Workflow\Shipment\AssignShippingDateListener' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\EventListener\Workflow\Shipment\AssignShippingDateListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/CoreBundle/EventListener/Workflow/Shipment/AssignShippingDateListener.php';

        return $container->privates['Sylius\\Bundle\\CoreBundle\\EventListener\\Workflow\\Shipment\\AssignShippingDateListener'] = new \Sylius\Bundle\CoreBundle\EventListener\Workflow\Shipment\AssignShippingDateListener(($container->services['sylius.shipping_date_assigner'] ?? $container->load('getSylius_ShippingDateAssignerService')));
    }
}
