<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContainsProductRuleUpdaterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Component\Core\Promotion\Updater\Rule\ContainsProductRuleUpdater' shared service.
     *
     * @return \Sylius\Component\Core\Promotion\Updater\Rule\ContainsProductRuleUpdater
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Promotion/Updater/Rule/ProductAwareRuleUpdaterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Promotion/Updater/Rule/ContainsProductRuleUpdater.php';

        return $container->services['Sylius\\Component\\Core\\Promotion\\Updater\\Rule\\ContainsProductRuleUpdater'] = new \Sylius\Component\Core\Promotion\Updater\Rule\ContainsProductRuleUpdater(($container->services['sylius.repository.promotion_rule'] ?? $container->load('getSylius_Repository_PromotionRuleService')));
    }
}
