<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAdminUserCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\AdminBundle\Command\CreateAdminUserCommand' shared service.
     *
     * @return \Sylius\Bundle\AdminBundle\Command\CreateAdminUserCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/HandleTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/AdminBundle/Command/CreateAdminUserCommand.php';

        $container->services['Sylius\\Bundle\\AdminBundle\\Command\\CreateAdminUserCommand'] = $instance = new \Sylius\Bundle\AdminBundle\Command\CreateAdminUserCommand(($container->services['messenger.default_bus'] ?? $container->getMessenger_DefaultBusService()), 'en_US');

        $instance->setName('sylius:admin-user:create');
        $instance->setDescription('Create a new admin user');

        return $instance;
    }
}
