<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGatewayConfigGroupsGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\PayumBundle\Validator\GroupsGenerator\GatewayConfigGroupsGenerator' shared service.
     *
     * @return \Sylius\Bundle\PayumBundle\Validator\GroupsGenerator\GatewayConfigGroupsGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/PayumBundle/Validator/GroupsGenerator/GatewayConfigGroupsGenerator.php';

        return $container->services['Sylius\\Bundle\\PayumBundle\\Validator\\GroupsGenerator\\GatewayConfigGroupsGenerator'] = new \Sylius\Bundle\PayumBundle\Validator\GroupsGenerator\GatewayConfigGroupsGenerator($container->parameters['sylius.payum.gateway_config.validation_groups']);
    }
}
