<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneratePromotionCouponHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\CommandHandler\Promotion\GeneratePromotionCouponHandler' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\CommandHandler\Promotion\GeneratePromotionCouponHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/CommandHandler/Promotion/GeneratePromotionCouponHandler.php';

        $a = ($container->services['sylius.promotion_coupon_generator'] ?? $container->load('getSylius_PromotionCouponGeneratorService'));

        if (isset($container->services['Sylius\\Bundle\\ApiBundle\\CommandHandler\\Promotion\\GeneratePromotionCouponHandler'])) {
            return $container->services['Sylius\\Bundle\\ApiBundle\\CommandHandler\\Promotion\\GeneratePromotionCouponHandler'];
        }

        return $container->services['Sylius\\Bundle\\ApiBundle\\CommandHandler\\Promotion\\GeneratePromotionCouponHandler'] = new \Sylius\Bundle\ApiBundle\CommandHandler\Promotion\GeneratePromotionCouponHandler(($container->services['sylius.repository.promotion'] ?? $container->load('getSylius_Repository_PromotionService')), $a);
    }
}
