<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductImageFilterProviderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\Provider\ProductImageFilterProviderInterface' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Provider\LiipProductImageFilterProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/Provider/ProductImageFilterProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/Provider/LiipProductImageFilterProvider.php';

        return $container->services['Sylius\\Bundle\\ApiBundle\\Provider\\ProductImageFilterProviderInterface'] = new \Sylius\Bundle\ApiBundle\Provider\LiipProductImageFilterProvider($container->parameters['liip_imagine.filter_sets']);
    }
}
