<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPathHiderDocumentationModifierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\ApiBundle\OpenApi\Documentation\PathHiderDocumentationModifier' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\OpenApi\Documentation\PathHiderDocumentationModifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/OpenApi/Documentation/DocumentationModifierInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/OpenApi/Documentation/PathHiderDocumentationModifier.php';

        return $container->privates['Sylius\\Bundle\\ApiBundle\\OpenApi\\Documentation\\PathHiderDocumentationModifier'] = new \Sylius\Bundle\ApiBundle\OpenApi\Documentation\PathHiderDocumentationModifier($container->parameters['sylius.api.paths_to_hide']);
    }
}
