<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductLowestPriceBeforeDiscountProcessorInterface2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\CoreBundle\PriceHistory\Processor\ProductLowestPriceBeforeDiscountProcessorInterface' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\PriceHistory\Processor\ProductLowestPriceBeforeDiscountProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/CoreBundle/PriceHistory/Processor/ProductLowestPriceBeforeDiscountProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/CoreBundle/PriceHistory/Processor/ProductLowestPriceBeforeDiscountProcessor.php';

        $a = ($container->services['sylius.repository.channel_pricing_log_entry'] ?? $container->load('getSylius_Repository_ChannelPricingLogEntryService'));

        if (isset($container->services['Sylius\\Bundle\\CoreBundle\\PriceHistory\\Processor\\ProductLowestPriceBeforeDiscountProcessorInterface'])) {
            return $container->services['Sylius\\Bundle\\CoreBundle\\PriceHistory\\Processor\\ProductLowestPriceBeforeDiscountProcessorInterface'];
        }
        $b = ($container->services['sylius.repository.channel'] ?? $container->getSylius_Repository_ChannelService());

        if (isset($container->services['Sylius\\Bundle\\CoreBundle\\PriceHistory\\Processor\\ProductLowestPriceBeforeDiscountProcessorInterface'])) {
            return $container->services['Sylius\\Bundle\\CoreBundle\\PriceHistory\\Processor\\ProductLowestPriceBeforeDiscountProcessorInterface'];
        }

        return $container->services['Sylius\\Bundle\\CoreBundle\\PriceHistory\\Processor\\ProductLowestPriceBeforeDiscountProcessorInterface'] = new \Sylius\Bundle\CoreBundle\PriceHistory\Processor\ProductLowestPriceBeforeDiscountProcessor($a, $b);
    }
}
