<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_CheckoutRedirectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.listener.checkout_redirect' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Checkout\CheckoutRedirectListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/CoreBundle/Checkout/CheckoutRedirectListener.php';

        $a = ($container->privates['sylius.router.checkout_state'] ?? $container->getSylius_Router_CheckoutStateService());

        if (isset($container->privates['sylius.listener.checkout_redirect'])) {
            return $container->privates['sylius.listener.checkout_redirect'];
        }

        return $container->privates['sylius.listener.checkout_redirect'] = new \Sylius\Bundle\CoreBundle\Checkout\CheckoutRedirectListener(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), $a, new \Symfony\Component\HttpFoundation\RequestMatcher('^/(?!'.$container->getEnv('string:resolve:SYLIUS_ADMIN_ROUTING_PATH_NAME').'|api/.*|api$|media/.*)[^/]++/checkout/.+'));
    }
}
