<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Validator_CountryCodeExistsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.validator.country_code_exists' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Validator\Constraints\CountryCodeExistsValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/CoreBundle/Validator/Constraints/CountryCodeExistsValidator.php';

        return $container->services['sylius.validator.country_code_exists'] = new \Sylius\Bundle\CoreBundle\Validator\Constraints\CountryCodeExistsValidator(($container->services['sylius.repository.country'] ?? $container->load('getSylius_Repository_CountryService')));
    }
}
