<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Form_Type_PromotionCouponGeneratorInstructionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.form.type.promotion_coupon_generator_instruction' shared service.
     *
     * @return \Sylius\Bundle\PromotionBundle\Form\Type\PromotionCouponGeneratorInstructionType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/DataMapperInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionCouponGeneratorInstructionType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/Extension/Core/DataMapper/DataMapper.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Promotion/Factory/PromotionCouponGeneratorInstructionFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Promotion/Factory/PromotionCouponGeneratorInstructionFactory.php';

        return $container->services['sylius.form.type.promotion_coupon_generator_instruction'] = new \Sylius\Bundle\PromotionBundle\Form\Type\PromotionCouponGeneratorInstructionType(new \Symfony\Component\Form\Extension\Core\DataMapper\DataMapper(), ($container->services['Sylius\\Component\\Promotion\\Factory\\PromotionCouponGeneratorInstructionFactoryInterface'] ?? ($container->services['Sylius\\Component\\Promotion\\Factory\\PromotionCouponGeneratorInstructionFactoryInterface'] = new \Sylius\Component\Promotion\Factory\PromotionCouponGeneratorInstructionFactory())), 'Sylius\\Component\\Promotion\\Generator\\PromotionCouponGeneratorInstruction', $container->parameters['sylius.form.type.promotion_coupon_generator_instruction.validation_groups']);
    }
}
