<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_TaxRateResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.tax_rate_resolver' shared service.
     *
     * @return \Sylius\Component\Taxation\Resolver\TaxRateResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Taxation/Resolver/TaxRateResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Taxation/Resolver/TaxRateResolver.php';

        $a = ($container->services['sylius.repository.tax_rate'] ?? $container->load('getSylius_Repository_TaxRateService'));

        if (isset($container->services['sylius.tax_rate_resolver'])) {
            return $container->services['sylius.tax_rate_resolver'];
        }

        return $container->services['sylius.tax_rate_resolver'] = new \Sylius\Component\Taxation\Resolver\TaxRateResolver($a, ($container->services['sylius.tax_rate_date_eligibility_checker'] ?? $container->load('getSylius_TaxRateDateEligibilityCheckerService')));
    }
}
