<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Repository_ProductReviewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.repository.product_review' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\Doctrine\ORM\ProductReviewRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Repository/ProductReviewRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductReviewRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->services['sylius.repository.product_review'])) {
            return $container->services['sylius.repository.product_review'];
        }

        return $container->services['sylius.repository.product_review'] = new \Sylius\Bundle\CoreBundle\Doctrine\ORM\ProductReviewRepository($a, $a->getClassMetadata('Sylius\\Component\\Core\\Model\\ProductReview'));
    }
}
