<?php

namespace ContainerI4ij0pE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Validator_AttributeTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.validator.attribute_type' shared service.
     *
     * @return \Sylius\Bundle\AttributeBundle\Validator\Constraints\AttributeTypeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/AttributeBundle/Validator/Constraints/AttributeTypeValidator.php';

        return $container->services['sylius.validator.attribute_type'] = new \Sylius\Bundle\AttributeBundle\Validator\Constraints\AttributeTypeValidator(($container->services['sylius.registry.attribute_type'] ?? $container->load('getSylius_Registry_AttributeTypeService')));
    }
}
