<?php

namespace ContainerNytzCg0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ay6o08OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ay6o08O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ay6o08O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'catalog_promotion_removal_failed' => ['privates', 'messenger.transport.catalog_promotion_removal_failed', 'getMessenger_Transport_CatalogPromotionRemovalFailedService', true],
            'main_failed' => ['privates', 'messenger.transport.main_failed', 'getMessenger_Transport_MainFailedService', true],
        ], [
            'catalog_promotion_removal_failed' => '?',
            'main_failed' => '?',
        ]);
    }
}
