<?php

namespace ContainerNytzCg0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssets_PackageAdminService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'assets._package_admin' shared service.
     *
     * @return \Sylius\Bundle\ThemeBundle\Asset\Package\PathPackage
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/VersionStrategy/JsonManifestVersionStrategy.php';

        return $container->privates['assets._package_admin'] = new \Sylius\Bundle\ThemeBundle\Asset\Package\PathPackage('', new \Symfony\Component\Asset\VersionStrategy\JsonManifestVersionStrategy((\dirname(__DIR__, 4).'/public/build/admin/manifest.json'), ($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), false), ($container->privates['sylius.theme.context.channel_based'] ?? $container->getSylius_Theme_Context_ChannelBasedService()), ($container->privates['Sylius\\Bundle\\ThemeBundle\\Asset\\PathResolverInterface'] ?? $container->getPathResolverInterfaceService()), ($container->privates['assets.context'] ?? $container->getAssets_ContextService()));
    }
}
