<?php

namespace ContainerNytzCg0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChannelPricingLogEntryEventListener2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\CoreBundle\PriceHistory\EventListener\ChannelPricingLogEntryEventListener' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\PriceHistory\EventListener\ChannelPricingLogEntryEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/CoreBundle/PriceHistory/EventListener/ChannelPricingLogEntryEventListener.php';

        $a = ($container->services['Sylius\\Bundle\\CoreBundle\\PriceHistory\\Processor\\ProductLowestPriceBeforeDiscountProcessorInterface'] ?? $container->load('getProductLowestPriceBeforeDiscountProcessorInterface2Service'));

        if (isset($container->services['Sylius\\Bundle\\CoreBundle\\PriceHistory\\EventListener\\ChannelPricingLogEntryEventListener'])) {
            return $container->services['Sylius\\Bundle\\CoreBundle\\PriceHistory\\EventListener\\ChannelPricingLogEntryEventListener'];
        }

        return $container->services['Sylius\\Bundle\\CoreBundle\\PriceHistory\\EventListener\\ChannelPricingLogEntryEventListener'] = new \Sylius\Bundle\CoreBundle\PriceHistory\EventListener\ChannelPricingLogEntryEventListener($a);
    }
}
