<?php

namespace ContainerNytzCg0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessengerDataPersisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\DataPersister\MessengerDataPersister' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\DataPersister\MessengerDataPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/DataPersister/MessengerDataPersister.php';

        $a = ($container->privates['api_platform.messenger.data_persister'] ?? $container->load('getApiPlatform_Messenger_DataPersisterService'));

        if (isset($container->services['Sylius\\Bundle\\ApiBundle\\DataPersister\\MessengerDataPersister'])) {
            return $container->services['Sylius\\Bundle\\ApiBundle\\DataPersister\\MessengerDataPersister'];
        }

        return $container->services['Sylius\\Bundle\\ApiBundle\\DataPersister\\MessengerDataPersister'] = new \Sylius\Bundle\ApiBundle\DataPersister\MessengerDataPersister($a);
    }
}
