<?php

namespace ContainerNytzCg0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayum_Action_ObtainCreditCardBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'payum.action.obtain_credit_card_builder' shared service.
     *
     * @return \Payum\Core\Bridge\Symfony\Builder\ObtainCreditCardActionBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/payum/core/Payum/Core/Bridge/Symfony/Builder/ObtainCreditCardActionBuilder.php';

        $a = ($container->services['.container.private.form.factory'] ?? $container->get_Container_Private_Form_FactoryService());

        if (isset($container->services['payum.action.obtain_credit_card_builder'])) {
            return $container->services['payum.action.obtain_credit_card_builder'];
        }

        return $container->services['payum.action.obtain_credit_card_builder'] = new \Payum\Core\Bridge\Symfony\Builder\ObtainCreditCardActionBuilder($a, ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
