<?php

namespace ContainerNytzCg0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromotionCouponPromotionFilterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\Filter\Doctrine\PromotionCouponPromotionFilter' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Filter\Doctrine\PromotionCouponPromotionFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Api/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Core/Bridge/Doctrine/Orm/Filter/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Core/Bridge/Doctrine/Orm/PropertyHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Core/Bridge/Doctrine/Common/PropertyHelperTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Core/Bridge/Doctrine/Orm/Filter/AbstractFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Core/Bridge/Doctrine/Orm/Filter/ContextAwareFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Core/Bridge/Doctrine/Orm/Filter/AbstractContextAwareFilter.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/Filter/Doctrine/PromotionCouponPromotionFilter.php';

        $a = ($container->privates['api_platform.symfony.iri_converter'] ?? $container->getApiPlatform_Symfony_IriConverterService());

        if (isset($container->services['Sylius\\Bundle\\ApiBundle\\Filter\\Doctrine\\PromotionCouponPromotionFilter'])) {
            return $container->services['Sylius\\Bundle\\ApiBundle\\Filter\\Doctrine\\PromotionCouponPromotionFilter'];
        }

        return $container->services['Sylius\\Bundle\\ApiBundle\\Filter\\Doctrine\\PromotionCouponPromotionFilter'] = new \Sylius\Bundle\ApiBundle\Filter\Doctrine\PromotionCouponPromotionFilter($a, ($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
