<?php

namespace ContainerNytzCg0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_AdminUser_Listener_UpdateUserEncoderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.admin_user.listener.update_user_encoder' shared service.
     *
     * @return \Sylius\Bundle\UserBundle\EventListener\UpdateUserEncoderListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/UserBundle/EventListener/UpdateUserEncoderListener.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['sylius.admin_user.listener.update_user_encoder'])) {
            return $container->privates['sylius.admin_user.listener.update_user_encoder'];
        }

        return $container->privates['sylius.admin_user.listener.update_user_encoder'] = new \Sylius\Bundle\UserBundle\EventListener\UpdateUserEncoderListener($a, 'argon2i', 'Sylius\\Component\\Core\\Model\\AdminUser', 'Sylius\\Component\\Core\\Model\\AdminUserInterface', '_password');
    }
}
