<?php

namespace ContainerNytzCg0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_OrderProcessing_OrderPromotionProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.order_processing.order_promotion_processor' shared service.
     *
     * @return \Sylius\Component\Core\OrderProcessing\OrderPromotionProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Order/Processor/OrderProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/OrderProcessing/OrderPromotionProcessor.php';

        $a = ($container->services['sylius.promotion_processor'] ?? $container->load('getSylius_PromotionProcessorService'));

        if (isset($container->services['sylius.order_processing.order_promotion_processor'])) {
            return $container->services['sylius.order_processing.order_promotion_processor'];
        }

        return $container->services['sylius.order_processing.order_promotion_processor'] = new \Sylius\Component\Core\OrderProcessing\OrderPromotionProcessor($a);
    }
}
