<?php

namespace ContainerNytzCg0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetImmutableNamesListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\CoreBundle\EventListener\Workflow\Order\SetImmutableNamesListener' shared service.
     *
     * @return \Sylius\Bundle\CoreBundle\EventListener\Workflow\Order\SetImmutableNamesListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/CoreBundle/EventListener/Workflow/Order/SetImmutableNamesListener.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Order/OrderItemNamesSetterInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Core/Order/OrderItemNamesSetter.php';

        return $container->privates['Sylius\\Bundle\\CoreBundle\\EventListener\\Workflow\\Order\\SetImmutableNamesListener'] = new \Sylius\Bundle\CoreBundle\EventListener\Workflow\Order\SetImmutableNamesListener(($container->services['sylius.order_item_names_setter'] ?? ($container->services['sylius.order_item_names_setter'] = new \Sylius\Component\Core\Order\OrderItemNamesSetter())));
    }
}
