<?php

namespace ContainerNytzCg0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Registry_TaxCalculatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sylius.registry.tax_calculator' shared service.
     *
     * @return \Sylius\Component\Registry\ServiceRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Taxation/Calculator/CalculatorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Taxation/Calculator/DefaultCalculator.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Component/Taxation/Calculator/DecimalCalculator.php';

        $container->services['sylius.registry.tax_calculator'] = $instance = new \Sylius\Component\Registry\ServiceRegistry('Sylius\\Component\\Taxation\\Calculator\\CalculatorInterface', 'Tax calculator');

        $instance->register('default', ($container->services['sylius.tax_calculator.default'] ?? ($container->services['sylius.tax_calculator.default'] = new \Sylius\Component\Taxation\Calculator\DefaultCalculator())));
        $instance->register('decimal', ($container->services['sylius.tax_calculator.decimal'] ?? ($container->services['sylius.tax_calculator.decimal'] = new \Sylius\Component\Taxation\Calculator\DecimalCalculator())));

        return $instance;
    }
}
