<?php

namespace ContainerNytzCg0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadTaxonImageActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ApiBundle\Controller\UploadTaxonImageAction' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Controller\UploadTaxonImageAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/Controller/UploadTaxonImageAction.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/Creator/ImageCreatorInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ApiBundle/Creator/TaxonImageCreator.php';

        return $container->services['Sylius\\Bundle\\ApiBundle\\Controller\\UploadTaxonImageAction'] = new \Sylius\Bundle\ApiBundle\Controller\UploadTaxonImageAction(new \Sylius\Bundle\ApiBundle\Creator\TaxonImageCreator(($container->services['sylius.factory.taxon_image'] ?? ($container->services['sylius.factory.taxon_image'] = new \Sylius\Component\Resource\Factory\Factory('Sylius\\Component\\Core\\Model\\TaxonImage'))), ($container->services['sylius.repository.taxon'] ?? $container->load('getSylius_Repository_TaxonService')), ($container->services['sylius.image_uploader'] ?? $container->load('getSylius_ImageUploaderService'))));
    }
}
