<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI4ij0pE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI4ij0pE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI4ij0pE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI4ij0pE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI4ij0pE\App_KernelDevDebugContainer([
    'container.build_hash' => 'I4ij0pE',
    'container.build_id' => '43f214a9',
    'container.build_time' => 1704395484,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI4ij0pE');
